Verify SVG output by diffing with known correct answers.

diff --git a/src/runtests b/src/runtests
--- a/src/runtests
+++ b/src/runtests
@@ -6,7 +6,16 @@ mypy --strict --module svgpanel || exit 1
 echo "Type-checking unittest.py"
 mypy --strict unittest.py || exit 1
 
+rm -f output/*.svg
 ./unittest.py all || exit 1
+
+for name in empty; do
+    echo "runtests: checking ${name}.svg"
+    if ! diff {correct,output}/${name}.svg; then
+        echo "FAIL(runtests): incorrect output for ${name}.svg"
+        exit 1
+    fi
+done
 
 cat pass.txt
 exit 0
